### ISSUE TITLE
Fix link targeting

### ISSUE THREAD

**Issue by davidwkaiser** [jmmastey/chicagoapprenticeships#9]
Hashrocket goes to "contact" page, it could go to apprentice page: https://hashrocket.com/careers/apprentice

Narrative Science goes to home page, could go here:
https://narrativescience.com/Resources/About-Narrative-Science/Careers

Dough is now a new company, no careers page that I can see. 

Devmynd link is dead, could point it here: 
https://www.devmynd.com/culture/careers/

Enove goes to the home page, it could go here: https://www.enova.com/careers/

**Comment by davidwkaiser** [comment]
BTW. These are issues I can handle, of course, but I want to confirm first.

**Comment by jmmastey** [comment]
Yeah, Dough never had a real careers page in any incarnation, which has always been a bit suspicious. I think Hashrocket sent me the contact page specifically as a way to funnel folks into their pipeline. The rest of those make sense.

**Comment by davidwkaiser** [comment]
OK, I'll go ahead and make those changes and submit a PR.

**Comment by jmmastey** [comment]
Thanks David!

**Comment by davidwkaiser** [comment]
Done, pull request waiting
